#make file

admin: adminEmployee.cpp employee.h employee.cpp salariedemployee.h salariedemployee.cpp administratoremployee.h administratoremployee.cpp
	g++ adminEmployee.cpp employee.h employee.cpp salariedemployee.h salariedemployee.cpp administratoremployee.h administratoremployee.cpp -o admin
